databases:
  - name: bkeki_cto_ada
    databaseName: bkeki_cto_ada
    user: bkeki_cto_ada
    plan: free

services:
  - type: web
    name: bkeki_cto_ada
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bkeki_cto_ada
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: XAI_API_KEY
        sync: false
